//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:08:54 AM CET 
//


package sk.toman.ubusws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dateBetween complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dateBetween">
 *   &lt;complexContent>
 *     &lt;extension base="{http://com.ibm.sk.ubus.ws}dateExpr">
 *       &lt;sequence>
 *         &lt;element name="after" type="{http://com.ibm.sk.ubus.ws}dateAfter" minOccurs="0"/>
 *         &lt;element name="before" type="{http://com.ibm.sk.ubus.ws}dateBefore" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dateBetween", propOrder = {
    "after",
    "before"
})
public class DateBetween
    extends DateExpr
{

    protected DateAfter after;
    protected DateBefore before;

    /**
     * Gets the value of the after property.
     * 
     * @return
     *     possible object is
     *     {@link DateAfter }
     *     
     */
    public DateAfter getAfter() {
        return after;
    }

    /**
     * Sets the value of the after property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAfter }
     *     
     */
    public void setAfter(DateAfter value) {
        this.after = value;
    }

    /**
     * Gets the value of the before property.
     * 
     * @return
     *     possible object is
     *     {@link DateBefore }
     *     
     */
    public DateBefore getBefore() {
        return before;
    }

    /**
     * Sets the value of the before property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateBefore }
     *     
     */
    public void setBefore(DateBefore value) {
        this.before = value;
    }

}
