//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:08:54 AM CET 
//


package sk.toman.ubusws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getContentItemByGuidAndVersion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getContentItemByGuidAndVersion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contentItemGuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contentItemScope" type="{http://com.ibm.sk.ubus.ws}contentItemScope" minOccurs="0"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getContentItemByGuidAndVersion", propOrder = {
    "contentItemGuid",
    "contentItemScope",
    "version"
})
public class GetContentItemByGuidAndVersion {

    protected String contentItemGuid;
    @XmlSchemaType(name = "string")
    protected ContentItemScope contentItemScope;
    protected int version;

    /**
     * Gets the value of the contentItemGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentItemGuid() {
        return contentItemGuid;
    }

    /**
     * Sets the value of the contentItemGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentItemGuid(String value) {
        this.contentItemGuid = value;
    }

    /**
     * Gets the value of the contentItemScope property.
     * 
     * @return
     *     possible object is
     *     {@link ContentItemScope }
     *     
     */
    public ContentItemScope getContentItemScope() {
        return contentItemScope;
    }

    /**
     * Sets the value of the contentItemScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentItemScope }
     *     
     */
    public void setContentItemScope(ContentItemScope value) {
        this.contentItemScope = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public int getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(int value) {
        this.version = value;
    }

}
