//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:08:54 AM CET 
//


package sk.toman.ubusws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IngestRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IngestRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processingProfile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="record" type="{http://com.ibm.sk.ubus.ws}RecordType" minOccurs="0"/>
 *         &lt;element name="contentKey" type="{http://com.ibm.sk.ubus.ws}ContentKeyType" minOccurs="0"/>
 *         &lt;element name="storageProfile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IngestRequestType", propOrder = {
    "processingProfile",
    "record",
    "contentKey",
    "storageProfile"
})
public class IngestRequestType {

    protected String processingProfile;
    protected RecordType record;
    protected ContentKeyType contentKey;
    protected String storageProfile;

    /**
     * Gets the value of the processingProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingProfile() {
        return processingProfile;
    }

    /**
     * Sets the value of the processingProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingProfile(String value) {
        this.processingProfile = value;
    }

    /**
     * Gets the value of the record property.
     * 
     * @return
     *     possible object is
     *     {@link RecordType }
     *     
     */
    public RecordType getRecord() {
        return record;
    }

    /**
     * Sets the value of the record property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordType }
     *     
     */
    public void setRecord(RecordType value) {
        this.record = value;
    }

    /**
     * Gets the value of the contentKey property.
     * 
     * @return
     *     possible object is
     *     {@link ContentKeyType }
     *     
     */
    public ContentKeyType getContentKey() {
        return contentKey;
    }

    /**
     * Sets the value of the contentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentKeyType }
     *     
     */
    public void setContentKey(ContentKeyType value) {
        this.contentKey = value;
    }

    /**
     * Gets the value of the storageProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorageProfile() {
        return storageProfile;
    }

    /**
     * Sets the value of the storageProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorageProfile(String value) {
        this.storageProfile = value;
    }

}
