//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:08:54 AM CET 
//


package sk.toman.ubusws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ingestByGuid complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ingestByGuid">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ingestByGuid" type="{http://com.ibm.sk.ubus.ws}IngestByGuidRequestType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ingestByGuid", propOrder = {
    "ingestByGuid"
})
public class IngestByGuid {

    protected IngestByGuidRequestType ingestByGuid;

    /**
     * Gets the value of the ingestByGuid property.
     * 
     * @return
     *     possible object is
     *     {@link IngestByGuidRequestType }
     *     
     */
    public IngestByGuidRequestType getIngestByGuid() {
        return ingestByGuid;
    }

    /**
     * Sets the value of the ingestByGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link IngestByGuidRequestType }
     *     
     */
    public void setIngestByGuid(IngestByGuidRequestType value) {
        this.ingestByGuid = value;
    }

}
