//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:08:54 AM CET 
//


package sk.toman.ubusws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sk.toman.ubusws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetContentItemSize_QNAME = new QName("http://com.ibm.sk.ubus.ws", "getContentItemSize");
    private final static QName _AbandonProcess_QNAME = new QName("http://com.ibm.sk.ubus.ws", "abandonProcess");
    private final static QName _FindRecords_QNAME = new QName("http://com.ibm.sk.ubus.ws", "findRecords");
    private final static QName _DeleteContentItemResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "deleteContentItemResponse");
    private final static QName _CancelSpaceAllocation_QNAME = new QName("http://com.ibm.sk.ubus.ws", "cancelSpaceAllocation");
    private final static QName _IngestByGuid_QNAME = new QName("http://com.ibm.sk.ubus.ws", "ingestByGuid");
    private final static QName _RetrieveACLForResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "retrieveACLForResponse");
    private final static QName _ContentItemNotFound_QNAME = new QName("http://com.ibm.sk.ubus.ws", "ContentItemNotFound");
    private final static QName _UpdatePathACLResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updatePathACLResponse");
    private final static QName _UpdateRecord_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateRecord");
    private final static QName _UpdateContentItemLatestResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateContentItemLatestResponse");
    private final static QName _RestartProcess_QNAME = new QName("http://com.ibm.sk.ubus.ws", "restartProcess");
    private final static QName _UpdateRecordMetadataItemsSyncResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateRecordMetadataItemsSyncResponse");
    private final static QName _StoreResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "storeResponse");
    private final static QName _FindGuidByExternalIdAndOwner_QNAME = new QName("http://com.ibm.sk.ubus.ws", "findGuidByExternalIdAndOwner");
    private final static QName _UpdateRecordMetadataItemsSync_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateRecordMetadataItemsSync");
    private final static QName _TestACLResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "testACLResponse");
    private final static QName _DisseminateResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "disseminateResponse");
    private final static QName _PathExistsResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "pathExistsResponse");
    private final static QName _Ingest_QNAME = new QName("http://com.ibm.sk.ubus.ws", "ingest");
    private final static QName _InsertContentItemResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "insertContentItemResponse");
    private final static QName _UpdatePathACL_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updatePathACL");
    private final static QName _UpdateACLResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateACLResponse");
    private final static QName _IngestByPath_QNAME = new QName("http://com.ibm.sk.ubus.ws", "ingestByPath");
    private final static QName _UpdateContentItemLatest_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateContentItemLatest");
    private final static QName _UpdateContentItemNewVersionResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateContentItemNewVersionResponse");
    private final static QName _DeleteContentItem_QNAME = new QName("http://com.ibm.sk.ubus.ws", "deleteContentItem");
    private final static QName _RecordRetrieveResult_QNAME = new QName("http://com.ibm.sk.ubus.ws", "recordRetrieveResult");
    private final static QName _StoreResult_QNAME = new QName("http://com.ibm.sk.ubus.ws", "storeResult");
    private final static QName _GetContentItemSizeResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "getContentItemSizeResponse");
    private final static QName _GetContentItemVersions_QNAME = new QName("http://com.ibm.sk.ubus.ws", "getContentItemVersions");
    private final static QName _FindRecordsResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "findRecordsResponse");
    private final static QName _SetRetentionEvent_QNAME = new QName("http://com.ibm.sk.ubus.ws", "setRetentionEvent");
    private final static QName _StoreUploaded_QNAME = new QName("http://com.ibm.sk.ubus.ws", "storeUploaded");
    private final static QName _RetrievePathACL_QNAME = new QName("http://com.ibm.sk.ubus.ws", "retrievePathACL");
    private final static QName _FindGuidByExternalIdAndOwnerResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "findGuidByExternalIdAndOwnerResponse");
    private final static QName _GetRecordByGuidResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "getRecordByGuidResponse");
    private final static QName _IngestByPathResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "ingestByPathResponse");
    private final static QName _InsertContentItemUploaded_QNAME = new QName("http://com.ibm.sk.ubus.ws", "insertContentItemUploaded");
    private final static QName _UpdateContentItemNewVersionUploadedResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateContentItemNewVersionUploadedResponse");
    private final static QName _GetProcessStatus_QNAME = new QName("http://com.ibm.sk.ubus.ws", "getProcessStatus");
    private final static QName _TestACL_QNAME = new QName("http://com.ibm.sk.ubus.ws", "testACL");
    private final static QName _UpdateACL_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateACL");
    private final static QName _NewerRecordIsStoredException_QNAME = new QName("http://com.ibm.sk.ubus.ws", "NewerRecordIsStoredException");
    private final static QName _GetContentItemVersionsResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "getContentItemVersionsResponse");
    private final static QName _GetProcessStatusesResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "getProcessStatusesResponse");
    private final static QName _GetContentItemByGuidAndVersionResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "getContentItemByGuidAndVersionResponse");
    private final static QName _GetContentItemByGuid_QNAME = new QName("http://com.ibm.sk.ubus.ws", "getContentItemByGuid");
    private final static QName _UpdateContentItemNewVersion_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateContentItemNewVersion");
    private final static QName _UpdateContentItemNewVersionUploaded_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateContentItemNewVersionUploaded");
    private final static QName _CreatePath_QNAME = new QName("http://com.ibm.sk.ubus.ws", "createPath");
    private final static QName _UpdateRecordMetadata_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateRecordMetadata");
    private final static QName _GetRecordByGuid_QNAME = new QName("http://com.ibm.sk.ubus.ws", "getRecordByGuid");
    private final static QName _TestPathACL_QNAME = new QName("http://com.ibm.sk.ubus.ws", "testPathACL");
    private final static QName _Request_QNAME = new QName("http://com.ibm.sk.ubus.ws", "request");
    private final static QName _UpdateRecordResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateRecordResponse");
    private final static QName _InsertContentItem_QNAME = new QName("http://com.ibm.sk.ubus.ws", "insertContentItem");
    private final static QName _PathExists_QNAME = new QName("http://com.ibm.sk.ubus.ws", "pathExists");
    private final static QName _GetProcessStatusResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "getProcessStatusResponse");
    private final static QName _GetContentItemByGuidResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "getContentItemByGuidResponse");
    private final static QName _Disseminate_QNAME = new QName("http://com.ibm.sk.ubus.ws", "disseminate");
    private final static QName _IngestResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "ingestResponse");
    private final static QName _RestartProcessResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "restartProcessResponse");
    private final static QName _RetrieveACLFor_QNAME = new QName("http://com.ibm.sk.ubus.ws", "retrieveACLFor");
    private final static QName _Response_QNAME = new QName("http://com.ibm.sk.ubus.ws", "response");
    private final static QName _IngestByGuidResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "ingestByGuidResponse");
    private final static QName _RetrievePathACLResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "retrievePathACLResponse");
    private final static QName _AllocateSpaceForUploadResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "allocateSpaceForUploadResponse");
    private final static QName _InsertContentItemUploadedResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "insertContentItemUploadedResponse");
    private final static QName _UpdateContentItemLatestUploaded_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateContentItemLatestUploaded");
    private final static QName _UpdateContentItemLatestUploadedResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateContentItemLatestUploadedResponse");
    private final static QName _UpdateRecordMetadataResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "updateRecordMetadataResponse");
    private final static QName _CancelSpaceAllocationResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "cancelSpaceAllocationResponse");
    private final static QName _DeleteRecord_QNAME = new QName("http://com.ibm.sk.ubus.ws", "deleteRecord");
    private final static QName _DeleteRecordResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "deleteRecordResponse");
    private final static QName _GetContentItemByGuidAndVersion_QNAME = new QName("http://com.ibm.sk.ubus.ws", "getContentItemByGuidAndVersion");
    private final static QName _SetRetentionEventResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "setRetentionEventResponse");
    private final static QName _CreatePathResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "createPathResponse");
    private final static QName _StoreUploadedResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "storeUploadedResponse");
    private final static QName _AllocateSpaceForUpload_QNAME = new QName("http://com.ibm.sk.ubus.ws", "allocateSpaceForUpload");
    private final static QName _AbandonProcessResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "abandonProcessResponse");
    private final static QName _GetProcessStatuses_QNAME = new QName("http://com.ibm.sk.ubus.ws", "getProcessStatuses");
    private final static QName _Store_QNAME = new QName("http://com.ibm.sk.ubus.ws", "store");
    private final static QName _TestPathACLResponse_QNAME = new QName("http://com.ibm.sk.ubus.ws", "testPathACLResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sk.toman.ubusws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RecordType }
     * 
     */
    public RecordType createRecordType() {
        return new RecordType();
    }

    /**
     * Create an instance of {@link DisseminationRequestType }
     * 
     */
    public DisseminationRequestType createDisseminationRequestType() {
        return new DisseminationRequestType();
    }

    /**
     * Create an instance of {@link UpdateRecordMetadataItemsRequestType }
     * 
     */
    public UpdateRecordMetadataItemsRequestType createUpdateRecordMetadataItemsRequestType() {
        return new UpdateRecordMetadataItemsRequestType();
    }

    /**
     * Create an instance of {@link ContentItemType }
     * 
     */
    public ContentItemType createContentItemType() {
        return new ContentItemType();
    }

    /**
     * Create an instance of {@link UpdateRecordMedataRequestType }
     * 
     */
    public UpdateRecordMedataRequestType createUpdateRecordMedataRequestType() {
        return new UpdateRecordMedataRequestType();
    }

    /**
     * Create an instance of {@link UpdateRecordMetadataItemsSyncResponse }
     * 
     */
    public UpdateRecordMetadataItemsSyncResponse createUpdateRecordMetadataItemsSyncResponse() {
        return new UpdateRecordMetadataItemsSyncResponse();
    }

    /**
     * Create an instance of {@link StoreResponse }
     * 
     */
    public StoreResponse createStoreResponse() {
        return new StoreResponse();
    }

    /**
     * Create an instance of {@link TestACLResponse }
     * 
     */
    public TestACLResponse createTestACLResponse() {
        return new TestACLResponse();
    }

    /**
     * Create an instance of {@link FindGuidByExternalIdAndOwner }
     * 
     */
    public FindGuidByExternalIdAndOwner createFindGuidByExternalIdAndOwner() {
        return new FindGuidByExternalIdAndOwner();
    }

    /**
     * Create an instance of {@link UpdateRecordMetadataItemsSync }
     * 
     */
    public UpdateRecordMetadataItemsSync createUpdateRecordMetadataItemsSync() {
        return new UpdateRecordMetadataItemsSync();
    }

    /**
     * Create an instance of {@link DisseminateResponse }
     * 
     */
    public DisseminateResponse createDisseminateResponse() {
        return new DisseminateResponse();
    }

    /**
     * Create an instance of {@link InsertContentItemResponse }
     * 
     */
    public InsertContentItemResponse createInsertContentItemResponse() {
        return new InsertContentItemResponse();
    }

    /**
     * Create an instance of {@link PathExistsResponse }
     * 
     */
    public PathExistsResponse createPathExistsResponse() {
        return new PathExistsResponse();
    }

    /**
     * Create an instance of {@link Ingest }
     * 
     */
    public Ingest createIngest() {
        return new Ingest();
    }

    /**
     * Create an instance of {@link GetContentItemSize }
     * 
     */
    public GetContentItemSize createGetContentItemSize() {
        return new GetContentItemSize();
    }

    /**
     * Create an instance of {@link FindRecords }
     * 
     */
    public FindRecords createFindRecords() {
        return new FindRecords();
    }

    /**
     * Create an instance of {@link AbandonProcess }
     * 
     */
    public AbandonProcess createAbandonProcess() {
        return new AbandonProcess();
    }

    /**
     * Create an instance of {@link DeleteContentItemResponse }
     * 
     */
    public DeleteContentItemResponse createDeleteContentItemResponse() {
        return new DeleteContentItemResponse();
    }

    /**
     * Create an instance of {@link CancelSpaceAllocation }
     * 
     */
    public CancelSpaceAllocation createCancelSpaceAllocation() {
        return new CancelSpaceAllocation();
    }

    /**
     * Create an instance of {@link IngestByGuid }
     * 
     */
    public IngestByGuid createIngestByGuid() {
        return new IngestByGuid();
    }

    /**
     * Create an instance of {@link RetrieveACLForResponse }
     * 
     */
    public RetrieveACLForResponse createRetrieveACLForResponse() {
        return new RetrieveACLForResponse();
    }

    /**
     * Create an instance of {@link ContentItemNotFound }
     * 
     */
    public ContentItemNotFound createContentItemNotFound() {
        return new ContentItemNotFound();
    }

    /**
     * Create an instance of {@link UpdatePathACLResponse }
     * 
     */
    public UpdatePathACLResponse createUpdatePathACLResponse() {
        return new UpdatePathACLResponse();
    }

    /**
     * Create an instance of {@link UpdateRecord }
     * 
     */
    public UpdateRecord createUpdateRecord() {
        return new UpdateRecord();
    }

    /**
     * Create an instance of {@link UpdateContentItemLatestResponse }
     * 
     */
    public UpdateContentItemLatestResponse createUpdateContentItemLatestResponse() {
        return new UpdateContentItemLatestResponse();
    }

    /**
     * Create an instance of {@link RestartProcess }
     * 
     */
    public RestartProcess createRestartProcess() {
        return new RestartProcess();
    }

    /**
     * Create an instance of {@link RecordRetrieveResult }
     * 
     */
    public RecordRetrieveResult createRecordRetrieveResult() {
        return new RecordRetrieveResult();
    }

    /**
     * Create an instance of {@link DeleteContentItem }
     * 
     */
    public DeleteContentItem createDeleteContentItem() {
        return new DeleteContentItem();
    }

    /**
     * Create an instance of {@link StoreResponseType }
     * 
     */
    public StoreResponseType createStoreResponseType() {
        return new StoreResponseType();
    }

    /**
     * Create an instance of {@link GetContentItemSizeResponse }
     * 
     */
    public GetContentItemSizeResponse createGetContentItemSizeResponse() {
        return new GetContentItemSizeResponse();
    }

    /**
     * Create an instance of {@link GetContentItemVersions }
     * 
     */
    public GetContentItemVersions createGetContentItemVersions() {
        return new GetContentItemVersions();
    }

    /**
     * Create an instance of {@link FindRecordsResponse }
     * 
     */
    public FindRecordsResponse createFindRecordsResponse() {
        return new FindRecordsResponse();
    }

    /**
     * Create an instance of {@link StoreUploaded }
     * 
     */
    public StoreUploaded createStoreUploaded() {
        return new StoreUploaded();
    }

    /**
     * Create an instance of {@link SetRetentionEvent }
     * 
     */
    public SetRetentionEvent createSetRetentionEvent() {
        return new SetRetentionEvent();
    }

    /**
     * Create an instance of {@link FindGuidByExternalIdAndOwnerResponse }
     * 
     */
    public FindGuidByExternalIdAndOwnerResponse createFindGuidByExternalIdAndOwnerResponse() {
        return new FindGuidByExternalIdAndOwnerResponse();
    }

    /**
     * Create an instance of {@link GetRecordByGuidResponse }
     * 
     */
    public GetRecordByGuidResponse createGetRecordByGuidResponse() {
        return new GetRecordByGuidResponse();
    }

    /**
     * Create an instance of {@link IngestByPathResponse }
     * 
     */
    public IngestByPathResponse createIngestByPathResponse() {
        return new IngestByPathResponse();
    }

    /**
     * Create an instance of {@link RetrievePathACL }
     * 
     */
    public RetrievePathACL createRetrievePathACL() {
        return new RetrievePathACL();
    }

    /**
     * Create an instance of {@link TestACL }
     * 
     */
    public TestACL createTestACL() {
        return new TestACL();
    }

    /**
     * Create an instance of {@link InsertContentItemUploaded }
     * 
     */
    public InsertContentItemUploaded createInsertContentItemUploaded() {
        return new InsertContentItemUploaded();
    }

    /**
     * Create an instance of {@link UpdateContentItemNewVersionUploadedResponse }
     * 
     */
    public UpdateContentItemNewVersionUploadedResponse createUpdateContentItemNewVersionUploadedResponse() {
        return new UpdateContentItemNewVersionUploadedResponse();
    }

    /**
     * Create an instance of {@link GetProcessStatus }
     * 
     */
    public GetProcessStatus createGetProcessStatus() {
        return new GetProcessStatus();
    }

    /**
     * Create an instance of {@link UpdatePathACL }
     * 
     */
    public UpdatePathACL createUpdatePathACL() {
        return new UpdatePathACL();
    }

    /**
     * Create an instance of {@link UpdateACLResponse }
     * 
     */
    public UpdateACLResponse createUpdateACLResponse() {
        return new UpdateACLResponse();
    }

    /**
     * Create an instance of {@link IngestByPath }
     * 
     */
    public IngestByPath createIngestByPath() {
        return new IngestByPath();
    }

    /**
     * Create an instance of {@link UpdateContentItemLatest }
     * 
     */
    public UpdateContentItemLatest createUpdateContentItemLatest() {
        return new UpdateContentItemLatest();
    }

    /**
     * Create an instance of {@link UpdateContentItemNewVersionResponse }
     * 
     */
    public UpdateContentItemNewVersionResponse createUpdateContentItemNewVersionResponse() {
        return new UpdateContentItemNewVersionResponse();
    }

    /**
     * Create an instance of {@link UpdateRecordRequestType }
     * 
     */
    public UpdateRecordRequestType createUpdateRecordRequestType() {
        return new UpdateRecordRequestType();
    }

    /**
     * Create an instance of {@link UpdateRecordResponse }
     * 
     */
    public UpdateRecordResponse createUpdateRecordResponse() {
        return new UpdateRecordResponse();
    }

    /**
     * Create an instance of {@link InsertContentItem }
     * 
     */
    public InsertContentItem createInsertContentItem() {
        return new InsertContentItem();
    }

    /**
     * Create an instance of {@link GetContentItemByGuidResponse }
     * 
     */
    public GetContentItemByGuidResponse createGetContentItemByGuidResponse() {
        return new GetContentItemByGuidResponse();
    }

    /**
     * Create an instance of {@link Disseminate }
     * 
     */
    public Disseminate createDisseminate() {
        return new Disseminate();
    }

    /**
     * Create an instance of {@link PathExists }
     * 
     */
    public PathExists createPathExists() {
        return new PathExists();
    }

    /**
     * Create an instance of {@link GetProcessStatusResponse }
     * 
     */
    public GetProcessStatusResponse createGetProcessStatusResponse() {
        return new GetProcessStatusResponse();
    }

    /**
     * Create an instance of {@link IngestResponse }
     * 
     */
    public IngestResponse createIngestResponse() {
        return new IngestResponse();
    }

    /**
     * Create an instance of {@link UpdateACL }
     * 
     */
    public UpdateACL createUpdateACL() {
        return new UpdateACL();
    }

    /**
     * Create an instance of {@link NewerRecordIsStoredException }
     * 
     */
    public NewerRecordIsStoredException createNewerRecordIsStoredException() {
        return new NewerRecordIsStoredException();
    }

    /**
     * Create an instance of {@link GetContentItemVersionsResponse }
     * 
     */
    public GetContentItemVersionsResponse createGetContentItemVersionsResponse() {
        return new GetContentItemVersionsResponse();
    }

    /**
     * Create an instance of {@link GetProcessStatusesResponse }
     * 
     */
    public GetProcessStatusesResponse createGetProcessStatusesResponse() {
        return new GetProcessStatusesResponse();
    }

    /**
     * Create an instance of {@link GetContentItemByGuidAndVersionResponse }
     * 
     */
    public GetContentItemByGuidAndVersionResponse createGetContentItemByGuidAndVersionResponse() {
        return new GetContentItemByGuidAndVersionResponse();
    }

    /**
     * Create an instance of {@link UpdateContentItemNewVersionUploaded }
     * 
     */
    public UpdateContentItemNewVersionUploaded createUpdateContentItemNewVersionUploaded() {
        return new UpdateContentItemNewVersionUploaded();
    }

    /**
     * Create an instance of {@link GetContentItemByGuid }
     * 
     */
    public GetContentItemByGuid createGetContentItemByGuid() {
        return new GetContentItemByGuid();
    }

    /**
     * Create an instance of {@link UpdateContentItemNewVersion }
     * 
     */
    public UpdateContentItemNewVersion createUpdateContentItemNewVersion() {
        return new UpdateContentItemNewVersion();
    }

    /**
     * Create an instance of {@link CreatePath }
     * 
     */
    public CreatePath createCreatePath() {
        return new CreatePath();
    }

    /**
     * Create an instance of {@link GetRecordByGuid }
     * 
     */
    public GetRecordByGuid createGetRecordByGuid() {
        return new GetRecordByGuid();
    }

    /**
     * Create an instance of {@link UpdateRecordMetadata }
     * 
     */
    public UpdateRecordMetadata createUpdateRecordMetadata() {
        return new UpdateRecordMetadata();
    }

    /**
     * Create an instance of {@link TestPathACL }
     * 
     */
    public TestPathACL createTestPathACL() {
        return new TestPathACL();
    }

    /**
     * Create an instance of {@link CreatePathResponse }
     * 
     */
    public CreatePathResponse createCreatePathResponse() {
        return new CreatePathResponse();
    }

    /**
     * Create an instance of {@link StoreUploadedResponse }
     * 
     */
    public StoreUploadedResponse createStoreUploadedResponse() {
        return new StoreUploadedResponse();
    }

    /**
     * Create an instance of {@link GetProcessStatuses }
     * 
     */
    public GetProcessStatuses createGetProcessStatuses() {
        return new GetProcessStatuses();
    }

    /**
     * Create an instance of {@link AllocateSpaceForUpload }
     * 
     */
    public AllocateSpaceForUpload createAllocateSpaceForUpload() {
        return new AllocateSpaceForUpload();
    }

    /**
     * Create an instance of {@link AbandonProcessResponse }
     * 
     */
    public AbandonProcessResponse createAbandonProcessResponse() {
        return new AbandonProcessResponse();
    }

    /**
     * Create an instance of {@link Store }
     * 
     */
    public Store createStore() {
        return new Store();
    }

    /**
     * Create an instance of {@link TestPathACLResponse }
     * 
     */
    public TestPathACLResponse createTestPathACLResponse() {
        return new TestPathACLResponse();
    }

    /**
     * Create an instance of {@link RestartProcessResponse }
     * 
     */
    public RestartProcessResponse createRestartProcessResponse() {
        return new RestartProcessResponse();
    }

    /**
     * Create an instance of {@link RetrieveACLFor }
     * 
     */
    public RetrieveACLFor createRetrieveACLFor() {
        return new RetrieveACLFor();
    }

    /**
     * Create an instance of {@link IngestByGuidResponse }
     * 
     */
    public IngestByGuidResponse createIngestByGuidResponse() {
        return new IngestByGuidResponse();
    }

    /**
     * Create an instance of {@link AllocateSpaceForUploadResponse }
     * 
     */
    public AllocateSpaceForUploadResponse createAllocateSpaceForUploadResponse() {
        return new AllocateSpaceForUploadResponse();
    }

    /**
     * Create an instance of {@link RetrievePathACLResponse }
     * 
     */
    public RetrievePathACLResponse createRetrievePathACLResponse() {
        return new RetrievePathACLResponse();
    }

    /**
     * Create an instance of {@link UpdateContentItemLatestUploaded }
     * 
     */
    public UpdateContentItemLatestUploaded createUpdateContentItemLatestUploaded() {
        return new UpdateContentItemLatestUploaded();
    }

    /**
     * Create an instance of {@link UpdateContentItemLatestUploadedResponse }
     * 
     */
    public UpdateContentItemLatestUploadedResponse createUpdateContentItemLatestUploadedResponse() {
        return new UpdateContentItemLatestUploadedResponse();
    }

    /**
     * Create an instance of {@link UpdateRecordMetadataResponse }
     * 
     */
    public UpdateRecordMetadataResponse createUpdateRecordMetadataResponse() {
        return new UpdateRecordMetadataResponse();
    }

    /**
     * Create an instance of {@link InsertContentItemUploadedResponse }
     * 
     */
    public InsertContentItemUploadedResponse createInsertContentItemUploadedResponse() {
        return new InsertContentItemUploadedResponse();
    }

    /**
     * Create an instance of {@link DeleteRecordResponse }
     * 
     */
    public DeleteRecordResponse createDeleteRecordResponse() {
        return new DeleteRecordResponse();
    }

    /**
     * Create an instance of {@link GetContentItemByGuidAndVersion }
     * 
     */
    public GetContentItemByGuidAndVersion createGetContentItemByGuidAndVersion() {
        return new GetContentItemByGuidAndVersion();
    }

    /**
     * Create an instance of {@link SetRetentionEventResponse }
     * 
     */
    public SetRetentionEventResponse createSetRetentionEventResponse() {
        return new SetRetentionEventResponse();
    }

    /**
     * Create an instance of {@link CancelSpaceAllocationResponse }
     * 
     */
    public CancelSpaceAllocationResponse createCancelSpaceAllocationResponse() {
        return new CancelSpaceAllocationResponse();
    }

    /**
     * Create an instance of {@link DeleteRecord }
     * 
     */
    public DeleteRecord createDeleteRecord() {
        return new DeleteRecord();
    }

    /**
     * Create an instance of {@link PathResponseType }
     * 
     */
    public PathResponseType createPathResponseType() {
        return new PathResponseType();
    }

    /**
     * Create an instance of {@link RetentionEventResponseType }
     * 
     */
    public RetentionEventResponseType createRetentionEventResponseType() {
        return new RetentionEventResponseType();
    }

    /**
     * Create an instance of {@link IngestByGuidRequestType }
     * 
     */
    public IngestByGuidRequestType createIngestByGuidRequestType() {
        return new IngestByGuidRequestType();
    }

    /**
     * Create an instance of {@link DateBefore }
     * 
     */
    public DateBefore createDateBefore() {
        return new DateBefore();
    }

    /**
     * Create an instance of {@link ContentItemDeleteResponseType }
     * 
     */
    public ContentItemDeleteResponseType createContentItemDeleteResponseType() {
        return new ContentItemDeleteResponseType();
    }

    /**
     * Create an instance of {@link UpdateRecordResponseType }
     * 
     */
    public UpdateRecordResponseType createUpdateRecordResponseType() {
        return new UpdateRecordResponseType();
    }

    /**
     * Create an instance of {@link ACLEntryType }
     * 
     */
    public ACLEntryType createACLEntryType() {
        return new ACLEntryType();
    }

    /**
     * Create an instance of {@link DeleteRecordResponseType }
     * 
     */
    public DeleteRecordResponseType createDeleteRecordResponseType() {
        return new DeleteRecordResponseType();
    }

    /**
     * Create an instance of {@link DateBetween }
     * 
     */
    public DateBetween createDateBetween() {
        return new DateBetween();
    }

    /**
     * Create an instance of {@link ContentItemRetrievalResponseType }
     * 
     */
    public ContentItemRetrievalResponseType createContentItemRetrievalResponseType() {
        return new ContentItemRetrievalResponseType();
    }

    /**
     * Create an instance of {@link ContentItemUpdateResponseType }
     * 
     */
    public ContentItemUpdateResponseType createContentItemUpdateResponseType() {
        return new ContentItemUpdateResponseType();
    }

    /**
     * Create an instance of {@link FindRecordResult }
     * 
     */
    public FindRecordResult createFindRecordResult() {
        return new FindRecordResult();
    }

    /**
     * Create an instance of {@link IngestRequestType }
     * 
     */
    public IngestRequestType createIngestRequestType() {
        return new IngestRequestType();
    }

    /**
     * Create an instance of {@link ProcessKeyType }
     * 
     */
    public ProcessKeyType createProcessKeyType() {
        return new ProcessKeyType();
    }

    /**
     * Create an instance of {@link ContentKeyType }
     * 
     */
    public ContentKeyType createContentKeyType() {
        return new ContentKeyType();
    }

    /**
     * Create an instance of {@link QueryRequestType }
     * 
     */
    public QueryRequestType createQueryRequestType() {
        return new QueryRequestType();
    }

    /**
     * Create an instance of {@link ACLResponseType }
     * 
     */
    public ACLResponseType createACLResponseType() {
        return new ACLResponseType();
    }

    /**
     * Create an instance of {@link LocationHrefType }
     * 
     */
    public LocationHrefType createLocationHrefType() {
        return new LocationHrefType();
    }

    /**
     * Create an instance of {@link ProcessStatusesResponse }
     * 
     */
    public ProcessStatusesResponse createProcessStatusesResponse() {
        return new ProcessStatusesResponse();
    }

    /**
     * Create an instance of {@link DateEquals }
     * 
     */
    public DateEquals createDateEquals() {
        return new DateEquals();
    }

    /**
     * Create an instance of {@link TestACLResponseType }
     * 
     */
    public TestACLResponseType createTestACLResponseType() {
        return new TestACLResponseType();
    }

    /**
     * Create an instance of {@link StoreRequestType }
     * 
     */
    public StoreRequestType createStoreRequestType() {
        return new StoreRequestType();
    }

    /**
     * Create an instance of {@link LocationContentType }
     * 
     */
    public LocationContentType createLocationContentType() {
        return new LocationContentType();
    }

    /**
     * Create an instance of {@link DateAfter }
     * 
     */
    public DateAfter createDateAfter() {
        return new DateAfter();
    }

    /**
     * Create an instance of {@link AllocationResponseType }
     * 
     */
    public AllocationResponseType createAllocationResponseType() {
        return new AllocationResponseType();
    }

    /**
     * Create an instance of {@link MetadataItemType }
     * 
     */
    public MetadataItemType createMetadataItemType() {
        return new MetadataItemType();
    }

    /**
     * Create an instance of {@link QueryType }
     * 
     */
    public QueryType createQueryType() {
        return new QueryType();
    }

    /**
     * Create an instance of {@link IngestResponseType }
     * 
     */
    public IngestResponseType createIngestResponseType() {
        return new IngestResponseType();
    }

    /**
     * Create an instance of {@link ProcessStatusResponse }
     * 
     */
    public ProcessStatusResponse createProcessStatusResponse() {
        return new ProcessStatusResponse();
    }

    /**
     * Create an instance of {@link ContentItemInsertResponseType }
     * 
     */
    public ContentItemInsertResponseType createContentItemInsertResponseType() {
        return new ContentItemInsertResponseType();
    }

    /**
     * Create an instance of {@link ContentItemVersionResponseType }
     * 
     */
    public ContentItemVersionResponseType createContentItemVersionResponseType() {
        return new ContentItemVersionResponseType();
    }

    /**
     * Create an instance of {@link IngestByPathRequestType }
     * 
     */
    public IngestByPathRequestType createIngestByPathRequestType() {
        return new IngestByPathRequestType();
    }

    /**
     * Create an instance of {@link ProcessStatusChangeResponse }
     * 
     */
    public ProcessStatusChangeResponse createProcessStatusChangeResponse() {
        return new ProcessStatusChangeResponse();
    }

    /**
     * Create an instance of {@link ExternalReferenceItem }
     * 
     */
    public ExternalReferenceItem createExternalReferenceItem() {
        return new ExternalReferenceItem();
    }

    /**
     * Create an instance of {@link ACLUpdateRequestType }
     * 
     */
    public ACLUpdateRequestType createACLUpdateRequestType() {
        return new ACLUpdateRequestType();
    }

    /**
     * Create an instance of {@link DigestType }
     * 
     */
    public DigestType createDigestType() {
        return new DigestType();
    }

    /**
     * Create an instance of {@link DisseminationResponseType }
     * 
     */
    public DisseminationResponseType createDisseminationResponseType() {
        return new DisseminationResponseType();
    }

    /**
     * Create an instance of {@link RecordType.Metadata }
     * 
     */
    public RecordType.Metadata createRecordTypeMetadata() {
        return new RecordType.Metadata();
    }

    /**
     * Create an instance of {@link RecordType.References }
     * 
     */
    public RecordType.References createRecordTypeReferences() {
        return new RecordType.References();
    }

    /**
     * Create an instance of {@link RecordType.ContentItems }
     * 
     */
    public RecordType.ContentItems createRecordTypeContentItems() {
        return new RecordType.ContentItems();
    }

    /**
     * Create an instance of {@link DisseminationRequestType.Uses }
     * 
     */
    public DisseminationRequestType.Uses createDisseminationRequestTypeUses() {
        return new DisseminationRequestType.Uses();
    }

    /**
     * Create an instance of {@link UpdateRecordMetadataItemsRequestType.Metadata }
     * 
     */
    public UpdateRecordMetadataItemsRequestType.Metadata createUpdateRecordMetadataItemsRequestTypeMetadata() {
        return new UpdateRecordMetadataItemsRequestType.Metadata();
    }

    /**
     * Create an instance of {@link ContentItemType.Uses }
     * 
     */
    public ContentItemType.Uses createContentItemTypeUses() {
        return new ContentItemType.Uses();
    }

    /**
     * Create an instance of {@link UpdateRecordMedataRequestType.Metadata }
     * 
     */
    public UpdateRecordMedataRequestType.Metadata createUpdateRecordMedataRequestTypeMetadata() {
        return new UpdateRecordMedataRequestType.Metadata();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetContentItemSize }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "getContentItemSize")
    public JAXBElement<GetContentItemSize> createGetContentItemSize(GetContentItemSize value) {
        return new JAXBElement<GetContentItemSize>(_GetContentItemSize_QNAME, GetContentItemSize.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbandonProcess }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "abandonProcess")
    public JAXBElement<AbandonProcess> createAbandonProcess(AbandonProcess value) {
        return new JAXBElement<AbandonProcess>(_AbandonProcess_QNAME, AbandonProcess.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindRecords }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "findRecords")
    public JAXBElement<FindRecords> createFindRecords(FindRecords value) {
        return new JAXBElement<FindRecords>(_FindRecords_QNAME, FindRecords.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteContentItemResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "deleteContentItemResponse")
    public JAXBElement<DeleteContentItemResponse> createDeleteContentItemResponse(DeleteContentItemResponse value) {
        return new JAXBElement<DeleteContentItemResponse>(_DeleteContentItemResponse_QNAME, DeleteContentItemResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelSpaceAllocation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "cancelSpaceAllocation")
    public JAXBElement<CancelSpaceAllocation> createCancelSpaceAllocation(CancelSpaceAllocation value) {
        return new JAXBElement<CancelSpaceAllocation>(_CancelSpaceAllocation_QNAME, CancelSpaceAllocation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IngestByGuid }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "ingestByGuid")
    public JAXBElement<IngestByGuid> createIngestByGuid(IngestByGuid value) {
        return new JAXBElement<IngestByGuid>(_IngestByGuid_QNAME, IngestByGuid.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrieveACLForResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "retrieveACLForResponse")
    public JAXBElement<RetrieveACLForResponse> createRetrieveACLForResponse(RetrieveACLForResponse value) {
        return new JAXBElement<RetrieveACLForResponse>(_RetrieveACLForResponse_QNAME, RetrieveACLForResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentItemNotFound }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "ContentItemNotFound")
    public JAXBElement<ContentItemNotFound> createContentItemNotFound(ContentItemNotFound value) {
        return new JAXBElement<ContentItemNotFound>(_ContentItemNotFound_QNAME, ContentItemNotFound.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePathACLResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updatePathACLResponse")
    public JAXBElement<UpdatePathACLResponse> createUpdatePathACLResponse(UpdatePathACLResponse value) {
        return new JAXBElement<UpdatePathACLResponse>(_UpdatePathACLResponse_QNAME, UpdatePathACLResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateRecord }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateRecord")
    public JAXBElement<UpdateRecord> createUpdateRecord(UpdateRecord value) {
        return new JAXBElement<UpdateRecord>(_UpdateRecord_QNAME, UpdateRecord.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateContentItemLatestResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateContentItemLatestResponse")
    public JAXBElement<UpdateContentItemLatestResponse> createUpdateContentItemLatestResponse(UpdateContentItemLatestResponse value) {
        return new JAXBElement<UpdateContentItemLatestResponse>(_UpdateContentItemLatestResponse_QNAME, UpdateContentItemLatestResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RestartProcess }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "restartProcess")
    public JAXBElement<RestartProcess> createRestartProcess(RestartProcess value) {
        return new JAXBElement<RestartProcess>(_RestartProcess_QNAME, RestartProcess.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateRecordMetadataItemsSyncResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateRecordMetadataItemsSyncResponse")
    public JAXBElement<UpdateRecordMetadataItemsSyncResponse> createUpdateRecordMetadataItemsSyncResponse(UpdateRecordMetadataItemsSyncResponse value) {
        return new JAXBElement<UpdateRecordMetadataItemsSyncResponse>(_UpdateRecordMetadataItemsSyncResponse_QNAME, UpdateRecordMetadataItemsSyncResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StoreResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "storeResponse")
    public JAXBElement<StoreResponse> createStoreResponse(StoreResponse value) {
        return new JAXBElement<StoreResponse>(_StoreResponse_QNAME, StoreResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindGuidByExternalIdAndOwner }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "findGuidByExternalIdAndOwner")
    public JAXBElement<FindGuidByExternalIdAndOwner> createFindGuidByExternalIdAndOwner(FindGuidByExternalIdAndOwner value) {
        return new JAXBElement<FindGuidByExternalIdAndOwner>(_FindGuidByExternalIdAndOwner_QNAME, FindGuidByExternalIdAndOwner.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateRecordMetadataItemsSync }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateRecordMetadataItemsSync")
    public JAXBElement<UpdateRecordMetadataItemsSync> createUpdateRecordMetadataItemsSync(UpdateRecordMetadataItemsSync value) {
        return new JAXBElement<UpdateRecordMetadataItemsSync>(_UpdateRecordMetadataItemsSync_QNAME, UpdateRecordMetadataItemsSync.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestACLResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "testACLResponse")
    public JAXBElement<TestACLResponse> createTestACLResponse(TestACLResponse value) {
        return new JAXBElement<TestACLResponse>(_TestACLResponse_QNAME, TestACLResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DisseminateResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "disseminateResponse")
    public JAXBElement<DisseminateResponse> createDisseminateResponse(DisseminateResponse value) {
        return new JAXBElement<DisseminateResponse>(_DisseminateResponse_QNAME, DisseminateResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PathExistsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "pathExistsResponse")
    public JAXBElement<PathExistsResponse> createPathExistsResponse(PathExistsResponse value) {
        return new JAXBElement<PathExistsResponse>(_PathExistsResponse_QNAME, PathExistsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ingest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "ingest")
    public JAXBElement<Ingest> createIngest(Ingest value) {
        return new JAXBElement<Ingest>(_Ingest_QNAME, Ingest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InsertContentItemResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "insertContentItemResponse")
    public JAXBElement<InsertContentItemResponse> createInsertContentItemResponse(InsertContentItemResponse value) {
        return new JAXBElement<InsertContentItemResponse>(_InsertContentItemResponse_QNAME, InsertContentItemResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePathACL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updatePathACL")
    public JAXBElement<UpdatePathACL> createUpdatePathACL(UpdatePathACL value) {
        return new JAXBElement<UpdatePathACL>(_UpdatePathACL_QNAME, UpdatePathACL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateACLResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateACLResponse")
    public JAXBElement<UpdateACLResponse> createUpdateACLResponse(UpdateACLResponse value) {
        return new JAXBElement<UpdateACLResponse>(_UpdateACLResponse_QNAME, UpdateACLResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IngestByPath }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "ingestByPath")
    public JAXBElement<IngestByPath> createIngestByPath(IngestByPath value) {
        return new JAXBElement<IngestByPath>(_IngestByPath_QNAME, IngestByPath.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateContentItemLatest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateContentItemLatest")
    public JAXBElement<UpdateContentItemLatest> createUpdateContentItemLatest(UpdateContentItemLatest value) {
        return new JAXBElement<UpdateContentItemLatest>(_UpdateContentItemLatest_QNAME, UpdateContentItemLatest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateContentItemNewVersionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateContentItemNewVersionResponse")
    public JAXBElement<UpdateContentItemNewVersionResponse> createUpdateContentItemNewVersionResponse(UpdateContentItemNewVersionResponse value) {
        return new JAXBElement<UpdateContentItemNewVersionResponse>(_UpdateContentItemNewVersionResponse_QNAME, UpdateContentItemNewVersionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteContentItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "deleteContentItem")
    public JAXBElement<DeleteContentItem> createDeleteContentItem(DeleteContentItem value) {
        return new JAXBElement<DeleteContentItem>(_DeleteContentItem_QNAME, DeleteContentItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecordRetrieveResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "recordRetrieveResult")
    public JAXBElement<RecordRetrieveResult> createRecordRetrieveResult(RecordRetrieveResult value) {
        return new JAXBElement<RecordRetrieveResult>(_RecordRetrieveResult_QNAME, RecordRetrieveResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StoreResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "storeResult")
    public JAXBElement<StoreResponseType> createStoreResult(StoreResponseType value) {
        return new JAXBElement<StoreResponseType>(_StoreResult_QNAME, StoreResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetContentItemSizeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "getContentItemSizeResponse")
    public JAXBElement<GetContentItemSizeResponse> createGetContentItemSizeResponse(GetContentItemSizeResponse value) {
        return new JAXBElement<GetContentItemSizeResponse>(_GetContentItemSizeResponse_QNAME, GetContentItemSizeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetContentItemVersions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "getContentItemVersions")
    public JAXBElement<GetContentItemVersions> createGetContentItemVersions(GetContentItemVersions value) {
        return new JAXBElement<GetContentItemVersions>(_GetContentItemVersions_QNAME, GetContentItemVersions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindRecordsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "findRecordsResponse")
    public JAXBElement<FindRecordsResponse> createFindRecordsResponse(FindRecordsResponse value) {
        return new JAXBElement<FindRecordsResponse>(_FindRecordsResponse_QNAME, FindRecordsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetRetentionEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "setRetentionEvent")
    public JAXBElement<SetRetentionEvent> createSetRetentionEvent(SetRetentionEvent value) {
        return new JAXBElement<SetRetentionEvent>(_SetRetentionEvent_QNAME, SetRetentionEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StoreUploaded }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "storeUploaded")
    public JAXBElement<StoreUploaded> createStoreUploaded(StoreUploaded value) {
        return new JAXBElement<StoreUploaded>(_StoreUploaded_QNAME, StoreUploaded.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrievePathACL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "retrievePathACL")
    public JAXBElement<RetrievePathACL> createRetrievePathACL(RetrievePathACL value) {
        return new JAXBElement<RetrievePathACL>(_RetrievePathACL_QNAME, RetrievePathACL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindGuidByExternalIdAndOwnerResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "findGuidByExternalIdAndOwnerResponse")
    public JAXBElement<FindGuidByExternalIdAndOwnerResponse> createFindGuidByExternalIdAndOwnerResponse(FindGuidByExternalIdAndOwnerResponse value) {
        return new JAXBElement<FindGuidByExternalIdAndOwnerResponse>(_FindGuidByExternalIdAndOwnerResponse_QNAME, FindGuidByExternalIdAndOwnerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRecordByGuidResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "getRecordByGuidResponse")
    public JAXBElement<GetRecordByGuidResponse> createGetRecordByGuidResponse(GetRecordByGuidResponse value) {
        return new JAXBElement<GetRecordByGuidResponse>(_GetRecordByGuidResponse_QNAME, GetRecordByGuidResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IngestByPathResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "ingestByPathResponse")
    public JAXBElement<IngestByPathResponse> createIngestByPathResponse(IngestByPathResponse value) {
        return new JAXBElement<IngestByPathResponse>(_IngestByPathResponse_QNAME, IngestByPathResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InsertContentItemUploaded }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "insertContentItemUploaded")
    public JAXBElement<InsertContentItemUploaded> createInsertContentItemUploaded(InsertContentItemUploaded value) {
        return new JAXBElement<InsertContentItemUploaded>(_InsertContentItemUploaded_QNAME, InsertContentItemUploaded.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateContentItemNewVersionUploadedResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateContentItemNewVersionUploadedResponse")
    public JAXBElement<UpdateContentItemNewVersionUploadedResponse> createUpdateContentItemNewVersionUploadedResponse(UpdateContentItemNewVersionUploadedResponse value) {
        return new JAXBElement<UpdateContentItemNewVersionUploadedResponse>(_UpdateContentItemNewVersionUploadedResponse_QNAME, UpdateContentItemNewVersionUploadedResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProcessStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "getProcessStatus")
    public JAXBElement<GetProcessStatus> createGetProcessStatus(GetProcessStatus value) {
        return new JAXBElement<GetProcessStatus>(_GetProcessStatus_QNAME, GetProcessStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestACL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "testACL")
    public JAXBElement<TestACL> createTestACL(TestACL value) {
        return new JAXBElement<TestACL>(_TestACL_QNAME, TestACL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateACL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateACL")
    public JAXBElement<UpdateACL> createUpdateACL(UpdateACL value) {
        return new JAXBElement<UpdateACL>(_UpdateACL_QNAME, UpdateACL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NewerRecordIsStoredException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "NewerRecordIsStoredException")
    public JAXBElement<NewerRecordIsStoredException> createNewerRecordIsStoredException(NewerRecordIsStoredException value) {
        return new JAXBElement<NewerRecordIsStoredException>(_NewerRecordIsStoredException_QNAME, NewerRecordIsStoredException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetContentItemVersionsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "getContentItemVersionsResponse")
    public JAXBElement<GetContentItemVersionsResponse> createGetContentItemVersionsResponse(GetContentItemVersionsResponse value) {
        return new JAXBElement<GetContentItemVersionsResponse>(_GetContentItemVersionsResponse_QNAME, GetContentItemVersionsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProcessStatusesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "getProcessStatusesResponse")
    public JAXBElement<GetProcessStatusesResponse> createGetProcessStatusesResponse(GetProcessStatusesResponse value) {
        return new JAXBElement<GetProcessStatusesResponse>(_GetProcessStatusesResponse_QNAME, GetProcessStatusesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetContentItemByGuidAndVersionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "getContentItemByGuidAndVersionResponse")
    public JAXBElement<GetContentItemByGuidAndVersionResponse> createGetContentItemByGuidAndVersionResponse(GetContentItemByGuidAndVersionResponse value) {
        return new JAXBElement<GetContentItemByGuidAndVersionResponse>(_GetContentItemByGuidAndVersionResponse_QNAME, GetContentItemByGuidAndVersionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetContentItemByGuid }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "getContentItemByGuid")
    public JAXBElement<GetContentItemByGuid> createGetContentItemByGuid(GetContentItemByGuid value) {
        return new JAXBElement<GetContentItemByGuid>(_GetContentItemByGuid_QNAME, GetContentItemByGuid.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateContentItemNewVersion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateContentItemNewVersion")
    public JAXBElement<UpdateContentItemNewVersion> createUpdateContentItemNewVersion(UpdateContentItemNewVersion value) {
        return new JAXBElement<UpdateContentItemNewVersion>(_UpdateContentItemNewVersion_QNAME, UpdateContentItemNewVersion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateContentItemNewVersionUploaded }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateContentItemNewVersionUploaded")
    public JAXBElement<UpdateContentItemNewVersionUploaded> createUpdateContentItemNewVersionUploaded(UpdateContentItemNewVersionUploaded value) {
        return new JAXBElement<UpdateContentItemNewVersionUploaded>(_UpdateContentItemNewVersionUploaded_QNAME, UpdateContentItemNewVersionUploaded.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreatePath }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "createPath")
    public JAXBElement<CreatePath> createCreatePath(CreatePath value) {
        return new JAXBElement<CreatePath>(_CreatePath_QNAME, CreatePath.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateRecordMetadata }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateRecordMetadata")
    public JAXBElement<UpdateRecordMetadata> createUpdateRecordMetadata(UpdateRecordMetadata value) {
        return new JAXBElement<UpdateRecordMetadata>(_UpdateRecordMetadata_QNAME, UpdateRecordMetadata.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRecordByGuid }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "getRecordByGuid")
    public JAXBElement<GetRecordByGuid> createGetRecordByGuid(GetRecordByGuid value) {
        return new JAXBElement<GetRecordByGuid>(_GetRecordByGuid_QNAME, GetRecordByGuid.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestPathACL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "testPathACL")
    public JAXBElement<TestPathACL> createTestPathACL(TestPathACL value) {
        return new JAXBElement<TestPathACL>(_TestPathACL_QNAME, TestPathACL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateRecordRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "request")
    public JAXBElement<UpdateRecordRequestType> createRequest(UpdateRecordRequestType value) {
        return new JAXBElement<UpdateRecordRequestType>(_Request_QNAME, UpdateRecordRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateRecordResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateRecordResponse")
    public JAXBElement<UpdateRecordResponse> createUpdateRecordResponse(UpdateRecordResponse value) {
        return new JAXBElement<UpdateRecordResponse>(_UpdateRecordResponse_QNAME, UpdateRecordResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InsertContentItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "insertContentItem")
    public JAXBElement<InsertContentItem> createInsertContentItem(InsertContentItem value) {
        return new JAXBElement<InsertContentItem>(_InsertContentItem_QNAME, InsertContentItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PathExists }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "pathExists")
    public JAXBElement<PathExists> createPathExists(PathExists value) {
        return new JAXBElement<PathExists>(_PathExists_QNAME, PathExists.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProcessStatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "getProcessStatusResponse")
    public JAXBElement<GetProcessStatusResponse> createGetProcessStatusResponse(GetProcessStatusResponse value) {
        return new JAXBElement<GetProcessStatusResponse>(_GetProcessStatusResponse_QNAME, GetProcessStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetContentItemByGuidResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "getContentItemByGuidResponse")
    public JAXBElement<GetContentItemByGuidResponse> createGetContentItemByGuidResponse(GetContentItemByGuidResponse value) {
        return new JAXBElement<GetContentItemByGuidResponse>(_GetContentItemByGuidResponse_QNAME, GetContentItemByGuidResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Disseminate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "disseminate")
    public JAXBElement<Disseminate> createDisseminate(Disseminate value) {
        return new JAXBElement<Disseminate>(_Disseminate_QNAME, Disseminate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IngestResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "ingestResponse")
    public JAXBElement<IngestResponse> createIngestResponse(IngestResponse value) {
        return new JAXBElement<IngestResponse>(_IngestResponse_QNAME, IngestResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RestartProcessResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "restartProcessResponse")
    public JAXBElement<RestartProcessResponse> createRestartProcessResponse(RestartProcessResponse value) {
        return new JAXBElement<RestartProcessResponse>(_RestartProcessResponse_QNAME, RestartProcessResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrieveACLFor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "retrieveACLFor")
    public JAXBElement<RetrieveACLFor> createRetrieveACLFor(RetrieveACLFor value) {
        return new JAXBElement<RetrieveACLFor>(_RetrieveACLFor_QNAME, RetrieveACLFor.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "response")
    public JAXBElement<Object> createResponse(Object value) {
        return new JAXBElement<Object>(_Response_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IngestByGuidResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "ingestByGuidResponse")
    public JAXBElement<IngestByGuidResponse> createIngestByGuidResponse(IngestByGuidResponse value) {
        return new JAXBElement<IngestByGuidResponse>(_IngestByGuidResponse_QNAME, IngestByGuidResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrievePathACLResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "retrievePathACLResponse")
    public JAXBElement<RetrievePathACLResponse> createRetrievePathACLResponse(RetrievePathACLResponse value) {
        return new JAXBElement<RetrievePathACLResponse>(_RetrievePathACLResponse_QNAME, RetrievePathACLResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AllocateSpaceForUploadResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "allocateSpaceForUploadResponse")
    public JAXBElement<AllocateSpaceForUploadResponse> createAllocateSpaceForUploadResponse(AllocateSpaceForUploadResponse value) {
        return new JAXBElement<AllocateSpaceForUploadResponse>(_AllocateSpaceForUploadResponse_QNAME, AllocateSpaceForUploadResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InsertContentItemUploadedResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "insertContentItemUploadedResponse")
    public JAXBElement<InsertContentItemUploadedResponse> createInsertContentItemUploadedResponse(InsertContentItemUploadedResponse value) {
        return new JAXBElement<InsertContentItemUploadedResponse>(_InsertContentItemUploadedResponse_QNAME, InsertContentItemUploadedResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateContentItemLatestUploaded }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateContentItemLatestUploaded")
    public JAXBElement<UpdateContentItemLatestUploaded> createUpdateContentItemLatestUploaded(UpdateContentItemLatestUploaded value) {
        return new JAXBElement<UpdateContentItemLatestUploaded>(_UpdateContentItemLatestUploaded_QNAME, UpdateContentItemLatestUploaded.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateContentItemLatestUploadedResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateContentItemLatestUploadedResponse")
    public JAXBElement<UpdateContentItemLatestUploadedResponse> createUpdateContentItemLatestUploadedResponse(UpdateContentItemLatestUploadedResponse value) {
        return new JAXBElement<UpdateContentItemLatestUploadedResponse>(_UpdateContentItemLatestUploadedResponse_QNAME, UpdateContentItemLatestUploadedResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateRecordMetadataResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "updateRecordMetadataResponse")
    public JAXBElement<UpdateRecordMetadataResponse> createUpdateRecordMetadataResponse(UpdateRecordMetadataResponse value) {
        return new JAXBElement<UpdateRecordMetadataResponse>(_UpdateRecordMetadataResponse_QNAME, UpdateRecordMetadataResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelSpaceAllocationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "cancelSpaceAllocationResponse")
    public JAXBElement<CancelSpaceAllocationResponse> createCancelSpaceAllocationResponse(CancelSpaceAllocationResponse value) {
        return new JAXBElement<CancelSpaceAllocationResponse>(_CancelSpaceAllocationResponse_QNAME, CancelSpaceAllocationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteRecord }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "deleteRecord")
    public JAXBElement<DeleteRecord> createDeleteRecord(DeleteRecord value) {
        return new JAXBElement<DeleteRecord>(_DeleteRecord_QNAME, DeleteRecord.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteRecordResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "deleteRecordResponse")
    public JAXBElement<DeleteRecordResponse> createDeleteRecordResponse(DeleteRecordResponse value) {
        return new JAXBElement<DeleteRecordResponse>(_DeleteRecordResponse_QNAME, DeleteRecordResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetContentItemByGuidAndVersion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "getContentItemByGuidAndVersion")
    public JAXBElement<GetContentItemByGuidAndVersion> createGetContentItemByGuidAndVersion(GetContentItemByGuidAndVersion value) {
        return new JAXBElement<GetContentItemByGuidAndVersion>(_GetContentItemByGuidAndVersion_QNAME, GetContentItemByGuidAndVersion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetRetentionEventResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "setRetentionEventResponse")
    public JAXBElement<SetRetentionEventResponse> createSetRetentionEventResponse(SetRetentionEventResponse value) {
        return new JAXBElement<SetRetentionEventResponse>(_SetRetentionEventResponse_QNAME, SetRetentionEventResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreatePathResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "createPathResponse")
    public JAXBElement<CreatePathResponse> createCreatePathResponse(CreatePathResponse value) {
        return new JAXBElement<CreatePathResponse>(_CreatePathResponse_QNAME, CreatePathResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StoreUploadedResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "storeUploadedResponse")
    public JAXBElement<StoreUploadedResponse> createStoreUploadedResponse(StoreUploadedResponse value) {
        return new JAXBElement<StoreUploadedResponse>(_StoreUploadedResponse_QNAME, StoreUploadedResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AllocateSpaceForUpload }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "allocateSpaceForUpload")
    public JAXBElement<AllocateSpaceForUpload> createAllocateSpaceForUpload(AllocateSpaceForUpload value) {
        return new JAXBElement<AllocateSpaceForUpload>(_AllocateSpaceForUpload_QNAME, AllocateSpaceForUpload.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbandonProcessResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "abandonProcessResponse")
    public JAXBElement<AbandonProcessResponse> createAbandonProcessResponse(AbandonProcessResponse value) {
        return new JAXBElement<AbandonProcessResponse>(_AbandonProcessResponse_QNAME, AbandonProcessResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProcessStatuses }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "getProcessStatuses")
    public JAXBElement<GetProcessStatuses> createGetProcessStatuses(GetProcessStatuses value) {
        return new JAXBElement<GetProcessStatuses>(_GetProcessStatuses_QNAME, GetProcessStatuses.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Store }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "store")
    public JAXBElement<Store> createStore(Store value) {
        return new JAXBElement<Store>(_Store_QNAME, Store.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestPathACLResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.ibm.sk.ubus.ws", name = "testPathACLResponse")
    public JAXBElement<TestPathACLResponse> createTestPathACLResponse(TestPathACLResponse value) {
        return new JAXBElement<TestPathACLResponse>(_TestPathACLResponse_QNAME, TestPathACLResponse.class, null, value);
    }

}
