//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:08:54 AM CET 
//


package sk.toman.ubusws;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for processStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="processStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="WAITING"/>
 *     &lt;enumeration value="IN_PROGRESS"/>
 *     &lt;enumeration value="FINISHED_WITH_SUCCESS"/>
 *     &lt;enumeration value="FINISHED_WITH_SUCCESS_AND_WARNINGS"/>
 *     &lt;enumeration value="TEMP_ERROR_DO_RETRY"/>
 *     &lt;enumeration value="ERROR"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "processStatus")
@XmlEnum
public enum ProcessStatus {

    WAITING,
    IN_PROGRESS,
    FINISHED_WITH_SUCCESS,
    FINISHED_WITH_SUCCESS_AND_WARNINGS,
    TEMP_ERROR_DO_RETRY,
    ERROR,
    UNKNOWN;

    public String value() {
        return name();
    }

    public static ProcessStatus fromValue(String v) {
        return valueOf(v);
    }

}
