//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:08:54 AM CET 
//


package sk.toman.ubusws;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queryOrderBy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="queryOrderBy">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DateCreated"/>
 *     &lt;enumeration value="DateModified"/>
 *     &lt;enumeration value="Title"/>
 *     &lt;enumeration value="Description"/>
 *     &lt;enumeration value="ExternalId"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "queryOrderBy")
@XmlEnum
public enum QueryOrderBy {

    @XmlEnumValue("DateCreated")
    DATE_CREATED("DateCreated"),
    @XmlEnumValue("DateModified")
    DATE_MODIFIED("DateModified"),
    @XmlEnumValue("Title")
    TITLE("Title"),
    @XmlEnumValue("Description")
    DESCRIPTION("Description"),
    @XmlEnumValue("ExternalId")
    EXTERNAL_ID("ExternalId");
    private final String value;

    QueryOrderBy(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QueryOrderBy fromValue(String v) {
        for (QueryOrderBy c: QueryOrderBy.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
