//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:08:54 AM CET 
//


package sk.toman.ubusws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ownerSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="externalIdIn" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="externalRecordTypeEquals" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="titleLikeExpr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="descriptionLikeExpr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="createdDateExpr" type="{http://com.ibm.sk.ubus.ws}dateExpr" minOccurs="0"/>
 *         &lt;element name="orderBy" type="{http://com.ibm.sk.ubus.ws}queryOrderBy" minOccurs="0"/>
 *         &lt;element name="dir" type="{http://com.ibm.sk.ubus.ws}queryOrderDir" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryType", propOrder = {
    "ownerSystem",
    "path",
    "externalIdIn",
    "externalRecordTypeEquals",
    "titleLikeExpr",
    "descriptionLikeExpr",
    "createdDateExpr",
    "orderBy",
    "dir"
})
public class QueryType {

    protected String ownerSystem;
    protected String path;
    @XmlElement(nillable = true)
    protected List<String> externalIdIn;
    protected String externalRecordTypeEquals;
    protected String titleLikeExpr;
    protected String descriptionLikeExpr;
    protected DateExpr createdDateExpr;
    @XmlSchemaType(name = "string")
    protected QueryOrderBy orderBy;
    @XmlSchemaType(name = "string")
    protected QueryOrderDir dir;

    /**
     * Gets the value of the ownerSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerSystem() {
        return ownerSystem;
    }

    /**
     * Sets the value of the ownerSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerSystem(String value) {
        this.ownerSystem = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the externalIdIn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalIdIn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalIdIn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getExternalIdIn() {
        if (externalIdIn == null) {
            externalIdIn = new ArrayList<String>();
        }
        return this.externalIdIn;
    }

    /**
     * Gets the value of the externalRecordTypeEquals property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalRecordTypeEquals() {
        return externalRecordTypeEquals;
    }

    /**
     * Sets the value of the externalRecordTypeEquals property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalRecordTypeEquals(String value) {
        this.externalRecordTypeEquals = value;
    }

    /**
     * Gets the value of the titleLikeExpr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleLikeExpr() {
        return titleLikeExpr;
    }

    /**
     * Sets the value of the titleLikeExpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleLikeExpr(String value) {
        this.titleLikeExpr = value;
    }

    /**
     * Gets the value of the descriptionLikeExpr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescriptionLikeExpr() {
        return descriptionLikeExpr;
    }

    /**
     * Sets the value of the descriptionLikeExpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescriptionLikeExpr(String value) {
        this.descriptionLikeExpr = value;
    }

    /**
     * Gets the value of the createdDateExpr property.
     * 
     * @return
     *     possible object is
     *     {@link DateExpr }
     *     
     */
    public DateExpr getCreatedDateExpr() {
        return createdDateExpr;
    }

    /**
     * Sets the value of the createdDateExpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateExpr }
     *     
     */
    public void setCreatedDateExpr(DateExpr value) {
        this.createdDateExpr = value;
    }

    /**
     * Gets the value of the orderBy property.
     * 
     * @return
     *     possible object is
     *     {@link QueryOrderBy }
     *     
     */
    public QueryOrderBy getOrderBy() {
        return orderBy;
    }

    /**
     * Sets the value of the orderBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryOrderBy }
     *     
     */
    public void setOrderBy(QueryOrderBy value) {
        this.orderBy = value;
    }

    /**
     * Gets the value of the dir property.
     * 
     * @return
     *     possible object is
     *     {@link QueryOrderDir }
     *     
     */
    public QueryOrderDir getDir() {
        return dir;
    }

    /**
     * Sets the value of the dir property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryOrderDir }
     *     
     */
    public void setDir(QueryOrderDir value) {
        this.dir = value;
    }

}
