//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:08:54 AM CET 
//


package sk.toman.ubusws;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recordScope.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="recordScope">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ALL"/>
 *     &lt;enumeration value="RECORD"/>
 *     &lt;enumeration value="CONTENT"/>
 *     &lt;enumeration value="HREFS"/>
 *     &lt;enumeration value="METADATA"/>
 *     &lt;enumeration value="EXTERNAL_REFERENCES"/>
 *     &lt;enumeration value="ALL_WITH_VALIDATION_DATA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "recordScope")
@XmlEnum
public enum RecordScope {

    ALL,
    RECORD,
    CONTENT,
    HREFS,
    METADATA,
    EXTERNAL_REFERENCES,
    ALL_WITH_VALIDATION_DATA;

    public String value() {
        return name();
    }

    public static RecordScope fromValue(String v) {
        return valueOf(v);
    }

}
