//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 08:08:54 AM CET 
//


package sk.toman.ubusws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for store complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="store">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="storeRequest" type="{http://com.ibm.sk.ubus.ws}StoreRequestType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "store", propOrder = {
    "storeRequest"
})
public class Store {

    protected StoreRequestType storeRequest;

    /**
     * Gets the value of the storeRequest property.
     * 
     * @return
     *     possible object is
     *     {@link StoreRequestType }
     *     
     */
    public StoreRequestType getStoreRequest() {
        return storeRequest;
    }

    /**
     * Sets the value of the storeRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreRequestType }
     *     
     */
    public void setStoreRequest(StoreRequestType value) {
        this.storeRequest = value;
    }

}
